export const PRODUCT_COPY = {
  dashboard: 'Dashboard',
  world: 'Your World',
  destinations: 'Destinations',
  destination: 'Destination',
  pathways: 'Pathways',
  plan: 'My Plan',
  flutterMode: 'Flutter Mode',
  documents: 'Documents',
  kolmariKlub: 'Kolmari Klub',
  costCalculator: 'Cost Calculator',
  greenbook: 'Greenbook',
  settings: 'Settings',
  matchScore: 'Match Score',
  communityFit: 'Community Fit',
  readiness: 'Move Readiness',
  timeline: 'Move Timeline',
  tracker: 'Progress Tracker',
  startCta: 'Build My Move Plan',
  executionCta: 'Enter Flutter Mode',
  exploreCta: 'Explore Countries',
  worldTitle: 'Explore Countries',
  destinationTitle: 'Explore This Destination',
} as const
